# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-20 09:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inspector', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idItem', models.IntegerField()),
                ('name', models.CharField(max_length=50)),
                ('context', models.CharField(max_length=20)),
                ('bonusList', models.CharField(blank=True, max_length=50)),
                ('itemSocket', models.IntegerField(choices=[(0, 'Head'), (1, 'Neck'), (2, 'Shoulder'), (3, 'Back'), (4, 'Chest'), (5, 'Tabard'), (6, 'Wrist'), (7, 'Hands'), (8, 'Waist'), (9, 'Legs'), (10, 'Feet'), (11, 'Finger1'), (12, 'Finger2'), (13, 'Trinket1'), (14, 'Trinket2'), (15, 'MainHand'), (16, 'OffHand')])),
            ],
        ),
        migrations.CreateModel(
            name='ItemStats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stat', models.IntegerField()),
                ('amount', models.IntegerField()),
                ('idItem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inspector.Item')),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('realm', models.CharField(max_length=20)),
                ('ilvl', models.IntegerField()),
                ('clase', models.IntegerField(choices=[('1', 'Guerrero'), ('2', 'Paladin'), ('3', 'Cazador'), ('4', 'Picaro'), ('5', 'Sacerdote'), ('6', 'Caballero de la Muerte'), ('7', 'Chaman'), ('8', 'Mago'), ('9', 'Brujo'), ('10', 'Monje'), ('11', 'Druida'), ('12', 'Cazador de demonios')])),
                ('race', models.IntegerField(choices=[('1', 'Humano'), ('2', 'Orco'), ('3', 'Enano'), ('4', 'Elfo de la Noche'), ('5', 'NoMuerto'), ('6', 'Tauren'), ('7', 'Gnomo'), ('8', 'Troll'), ('9', 'Goblin'), ('10', 'Elfo de Sangre'), ('11', 'Draenei'), ('22', 'Worgen'), ('24', 'Pandaren'), ('25', 'Pandaren'), ('26', 'Pandaren')])),
                ('gender', models.IntegerField(choices=[('0', 'M'), ('1', 'F')])),
                ('lvl', models.IntegerField()),
                ('faction', models.IntegerField(choices=[('0', 'Alianza'), ('1', 'Horda')])),
                ('image', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PlayerItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idItem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inspector.Item')),
                ('idPlayer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inspector.Player')),
            ],
        ),
        migrations.CreateModel(
            name='PlayerItemHistoric',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('idItem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inspector.Item')),
                ('idPlayer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inspector.Player')),
            ],
        ),
    ]
