# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-20 10:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspector', '0002_item_itemstats_player_playeritem_playeritemhistoric'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='itemSocket',
            field=models.IntegerField(choices=[(0, 'Head'), (1, 'Neck'), (2, 'Shoulder'), (3, 'Back'), (4, 'Chest'), (5, 'Tabard'), (6, 'Wrist'), (7, 'Hands'), (8, 'Waist'), (9, 'Legs'), (10, 'Feet'), (11, 'Finger1'), (12, 'Finger2'), (13, 'Trinket1'), (14, 'Trinket2'), (15, 'MainHand'), (16, 'OffHand'), (17, 'shirt')]),
        ),
    ]
