# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-20 12:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspector', '0004_auto_20160920_1035'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='ilvl',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
