# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-20 12:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspector', '0005_item_ilvl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='clase',
            field=models.IntegerField(choices=[(1, b'Guerrero'), (2, b'Paladin'), (3, b'Cazador'), (4, b'Picaro'), (5, b'Sacerdote'), (6, b'Caballero de la Muerte'), (7, b'Chaman'), (8, b'Mago'), (9, b'Brujo'), (10, b'Monje'), (11, b'Druida'), (12, b'Cazador de demonios')]),
        ),
        migrations.AlterField(
            model_name='player',
            name='faction',
            field=models.IntegerField(choices=[(0, b'Alianza'), (1, b'Horda')]),
        ),
        migrations.AlterField(
            model_name='player',
            name='gender',
            field=models.IntegerField(choices=[(0, b'M'), (1, b'F')]),
        ),
        migrations.AlterField(
            model_name='player',
            name='race',
            field=models.IntegerField(choices=[(1, b'Humano'), (2, b'Orco'), (3, b'Enano'), (4, b'Elfo de la Noche'), (5, b'NoMuerto'), (6, b'Tauren'), (7, b'Gnomo'), (8, b'Troll'), (9, b'Goblin'), (10, b'Elfo de Sangre'), (11, b'Draenei'), (22, b'Worgen'), (24, b'Pandaren'), (25, b'Pandaren'), (26, b'Pandaren')]),
        ),
    ]
