# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-20 15:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inspector', '0006_auto_20160920_1254'),
    ]

    operations = [
        migrations.CreateModel(
            name='Artifact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idArtifact', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
                ('idPlayer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inspector.Player')),
            ],
        ),
        migrations.CreateModel(
            name='ArtifactRelic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idArtifact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inspector.Artifact')),
                ('idPlayer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inspector.Player')),
            ],
        ),
        migrations.CreateModel(
            name='Relic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idRelic', models.IntegerField()),
                ('context', models.IntegerField()),
                ('bonusList', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Trait',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idTrait', models.IntegerField()),
                ('rank', models.IntegerField()),
                ('idArtifact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inspector.Artifact')),
                ('idPlayer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inspector.Player')),
            ],
        ),
    ]
