# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-21 09:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspector', '0007_artifact_artifactrelic_relic_trait'),
    ]

    operations = [
        migrations.AddField(
            model_name='artifactrelic',
            name='socket',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='item',
            name='itemSocket',
            field=models.IntegerField(choices=[(0, b'Head'), (1, b'Neck'), (2, b'Shoulder'), (3, b'Back'), (4, b'Chest'), (5, b'Tabard'), (6, b'Wrist'), (7, b'Hands'), (8, b'Waist'), (9, b'Legs'), (10, b'Feet'), (11, b'Finger1'), (12, b'Finger2'), (13, b'Trinket1'), (14, b'Trinket2'), (15, b'MainHand'), (16, b'OffHand'), (17, b'Shirt')]),
        ),
    ]
