# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-21 12:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inspector', '0008_auto_20160921_0927'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArtifactRelicHistoric',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('socket', models.IntegerField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('idArtifact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inspector.Artifact')),
                ('idPlayer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inspector.Player')),
                ('idRelic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inspector.Relic')),
            ],
        ),
        migrations.AddField(
            model_name='artifactrelic',
            name='idRelic',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='inspector.Relic'),
            preserve_default=False,
        ),
    ]
