# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-22 14:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inspector', '0010_auto_20160921_1512'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ItemStats',
            new_name='ItemStat',
        ),
    ]
